apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: liwa
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      port: 80
      protocol: HTTP
    - name: https
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
        # kinds:
        #   - kind: HTTPRoute
        #     group: gateway.envoyproxy.io
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            # 这个group 字段非常重要 ！
            name: liwa-com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: liwa
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: liwa
  labels:
    app: backend
    service: backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: liwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      serviceAccountName: backend
      containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: backend
          ports:
            - containerPort: 80
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
  namespace: liwa
spec:
  parentRefs:
    - name: eg
      sectionName: https
  hostnames:
    - "www12.liwa.com"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: backend
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: ReferenceGrant
# metadata:
#   name: infra-gateways
#   namespace: liwa
# spec:
#   from:
#   - group: gateway.networking.k8s.io
#     kind: Gateway
#     namespace: envoy-gateway-system
#   to:
#   - group: gateway.networking.k8s.io
#     kind: HTTPRoute